name: Build install package

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . -t 'pipa-fedora-builder'

    - name: Build the Fedora image
      run: docker run --privileged -v "$(pwd)"/images:/build/images -v "/dev:/dev" pipa-fedora-builder

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: nightly-${{ steps.date.outputs.date }}
        name: Nightly ${{ steps.date.outputs.date }}
        files: images/*.zip
