name: Docker Image CI

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t 'nabu-fedora-builder'
    - name: Build the Fedora image
      run: docker run --privileged -v "$(pwd)"/images:/build/images -v "/dev:/dev" nabu-fedora-builder
    - uses: actions/upload-artifact@v3
      with:
        name: fedora-root-efi
        path: images/*.zip
